contrib: android: Dockerfile: fix ownership of COPY
Resolves:

    ERROR: Could not open requirements file: [Errno 13] Permission
    denied: '/opt/deterministic-build/requirements-build-base.txt'

(cherry picked from commit 202ea2870c1b55c0ac84b4b7570a36af2805b475)