interface.py: rm broken dead code
As it's failing due to relative imports, this might have been broken since py2->py3 migration.
```
$ python3 ./electrum/interface.py
Traceback (most recent call last):
  File "/home/user/wspace/electrum/./electrum/interface.py", line 31, in <module>
    import asyncio
  File "/usr/lib/python3.13/asyncio/__init__.py", line 8, in <module>
    from .base_events import *
  File "/usr/lib/python3.13/asyncio/base_events.py", line 18, in <module>
    import concurrent.futures
  File "/usr/lib/python3.13/concurrent/futures/__init__.py", line 8, in <module>
    from concurrent.futures._base import (FIRST_COMPLETED,
    ...<9 lines>...
                                          as_completed)
  File "/usr/lib/python3.13/concurrent/futures/_base.py", line 7, in <module>
    import logging
  File "/home/user/wspace/electrum/electrum/logging.py", line 6, in <module>
    import logging.handlers
ModuleNotFoundError: No module named 'logging.handlers'; 'logging' is not a package
```

(cherry picked from commit baf9a1d976b606b9611b42849d39a4462d06f9a5)